[build]
  base = "client"
  command = "npm install --legacy-peer-deps --force && CI=false npm run build"
  
[build.environment]
  NODE_VERSION = "20.18.0"
  NETLIFY = "true"
  NEXT_TELEMETRY_DISABLED = "1"
  NPM_FLAGS = "--legacy-peer-deps"
  NEXT_PRIVATE_STANDALONE = "false"
  
[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/image"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
